spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    schema: classpath:db/schema.sql
    url: jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE
    username: sa

benchmark:
  resultDir: benchmark_result